title: "The Higher-Resolution Hypothesis"
description: "Autism as a distributed neural architecture producing higher-resolution cognition through overlapping network activation."
theme: minima
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
  syntax_highlighter: rouge
permalink: pretty
